### ISSUE TITLE
Does it work only in 1:1 aspect ratio?

### ISSUE THREAD

**Issue by Cedri4** [logtd/ComfyUI-Veevee#2]
When I try to use a video in anything other than 1:1 aspect ratio I get this error:
![image](https://github.com/user-attachments/assets/7748cd37-f1cd-4533-898b-177c05a1976b)
![image](https://github.com/user-attachments/assets/c78f92a7-dac2-4f2b-be26-14c8840dfc74)

I used width 852 and with 512.
For some reason 768x512 works

**Comment by logtd** [comment]
I've used it with other aspects, e.g. 16:9. You should make sure your dimensions are divisible by 8 (general rule of thumb for most models)

**Comment by Cedri4** [comment]
![image](https://github.com/user-attachments/assets/41a465fe-8da5-4c25-9f9e-743d5e3cdf90)
I tried with 512x912 for 9:16 and it still doesn't work.

**Comment by Cedri4** [comment]
Hmm, 576x1024 seems to work fine

**Comment by Cedri4** [comment]
Also @logtd it would be nice to have the description to your nodes since in my case it is quite complex to understand which nodes does what.
Built-in nodes already have some sort of a description:
![image](https://github.com/user-attachments/assets/17ef0161-43ef-4733-8422-0ac28c62702d)

**Comment by logtd** [comment]
Thanks, I'll take a look at tooltips.

It looks like your error is occurring when using unimatch. I've added in SEA Raft, which is a new optical flow processor that has better results imo. 

You can use it by using the `Get Raft Flow` node and placing SEA Raft in the `ComfyUI/models/raft` directory.
The model checkpoint can be found here: https://github.com/princeton-vl/SEA-RAFT

I'll add them to huggingface when I get time.
